Fix presentations in IE
sara-sabr/ITStrategy pull request #1636
Opened 2021-03-30 20:59 UTC by gabrielcossette

You can test in my fork (as Jekyll doesn't render presentations locally correctly anyway):
https://gabrielcossette.github.io/ITStrategy/presentations.html

Explanation: The native Web API "URLSearchParams" isn't supported by Internet Explorer.

I replaced it with a "[polyfill](https://en.wikipedia.org/wiki/Polyfill_(programming))" I found (while learning what is a polyfill at the same time 😄)

Fixes #1628

2021-04-06 20:02 UTC, smellems requested changes
Tested with https://gabrielcossette.github.io/ITStrategy/presentations.html using IE11

Presentations seem to have alot of missing (blank) slides..

![image](https://user-images.githubusercontent.com/2353299/113771548-7fc78900-96f1-11eb-9d12-cb7d2fcbab8d.png)

2021-04-28 18:49 UTC, gabrielcossette commented
(Sorry, my PR has been updated but I forgot to tell you before I left for the week)

Now the PR does a redirection to Edge instead:

**Actions**

1. Information message shown (depending on language of the site being viewed) :

English:

> We recommend to use Edge, Firefox and other modern browsers instead of Internet Explorer.
> 
> We'll now open this website in Edge for an optimal experience.

French:

> Nous recommandons d'utiliser Edge, Firefox et autres navigateurs modernes au lieu d'Internet Explorer.
> 
> Nous allons maintenant ouvrir ce site dans Edge pour une expérience optimale.

2. Edge launched and same page opened (presentation)

3. This page opened by Internet Explorer (now in the background):

[The website you were trying to reach doesn't work with Internet Explorer](https://go.microsoft.com/fwlink/?linkid=2135547)

Feel free to tweak and merge 👍

2021-04-28 18:55 UTC, gabrielcossette commented
FYI, CI check fails because of some links (not part of PR).

2021-04-28 19:01 UTC, gabrielcossette commented
And you can test with these links:

EN: https://gabrielcossette.github.io/ITStrategy/presentation.html?markdown=en/SLF.md

FR: https://gabrielcossette.github.io/ITStrategy/presentation.html?markdown=fr/SLF.md

2021-05-18 22:11 UTC, gcharest approved these changes
Fixes were made that address your request @smellems 

Please confirm if this is working appropriately so we can merge 😄

2021-05-19 12:53 UTC, smellems approved these changes

2021-05-19 12:54 UTC, merged