NPM Update and NPM Audit Fix
sara-sabr/ITStrategy pull request #1714
Opened 2021-05-18 15:06 UTC by smellems

2021-05-18 15:07 UTC, gcharest approved these changes

2021-05-18 15:08 UTC, gcharest requested changes
Broke FR cspell

2021-05-19 14:36 UTC, gcharest commented
Closes #1702 and #1700

2021-05-25 15:50 UTC, smellems commented
@gcharest I updated CSpell to the latest version as is incompatible with the dictionaries after the original update.

I also updated other packages in the json.

Fixed some new build issues.

When I run the build locally (docker) I get some `EACCES: permission denied` warnings, but the build can still pass.
It's trying to access cspell is trying to access `/root/.config/configstore` and glob is trying to access `/root/.npm/_logs`.

I don't see those errors on Github Actions build.

Build is currently failing because of dead links to Buy and Sell.

2021-06-02 12:42 UTC, gcharest approved these changes

2021-06-02 12:42 UTC, merged