User Engagement in Service Delivery blog
sara-sabr/ITStrategy pull request #1887
Opened 2021-09-01 19:23 UTC by ElminaIusifova

2021-09-01 19:34 UTC, ElminaIusifova commented
@gabrielcossette @gcharest  the length of the card is too long on the webpage for this blog, can one of you help me to fix it please? Thanks

2021-09-03 12:37 UTC, gcharest commented
> @gabrielcossette @gcharest the length of the card is too long on the webpage for this blog, can one of you help me to fix it please? Thanks

Oh, yes! Absolutely, I think it's due to the fact we haven't identified any "excerpt" part. What would you like to display on the card? The first two sentences only?

2021-09-03 13:34 UTC, remyb2canada approved these changes
Great work Elmina!

2021-09-07 12:45 UTC, ElminaIusifova commented
@gcharest Yes please, first 2-3 sentences as long as the card with this blog is the same length as others. Thank you

2021-09-10 18:31 UTC, gabrielcossette approved these changes
Sorry for the delay.
Great blog post! I reviewed and made some adjustments. Feel free to change them back or else.

2021-09-10 19:01 UTC, gcharest requested changes
Making a few changes to adjust the blog card!

2021-09-10 19:16 UTC, gcharest requested changes
All good, tests will pass once we merge #1860.

- [ ] Need French translation! :smile:

2021-09-10 19:16 UTC, gabrielcossette commented
> 
> 
> Making a few changes to adjust the blog card!

Thanks for fixing this Guillaume, I forgot about it! 🙂

2021-09-13 14:10 UTC, gcharest approved these changes

2021-09-13 16:46 UTC, gabrielcossette commented on _posts/en/2021-08-18-user-engagement-in-service-delivery.md
> +With the feedback received, we tried to iterate the overall experience for the user.
I forgot to leave a comment on this. Not sure "iterate" is the right verb here, but I understand the idea behind it. Maybe it needs rephrasing.

2021-09-16 15:35 UTC, remyb2canada commented on _posts/en/2021-09-16-user-engagement-in-service-delivery.md
> +To design for a public servant while being public servants ourselves, it is so easy to create a self-referential product as if we are making the product only for us, when in fact the target audience
I REALLY REALLY LIKE this section.
Nice

2021-09-16 15:49 UTC, remyb2canada approved these changes

2021-09-16 15:49 UTC, remyb2canada commented on _posts/en/2021-09-16-user-engagement-in-service-delivery.md
> +To design for a public servant while being public servants ourselves, it is so easy to create a self-referential product as if we are making the product only for us, when in fact the target audience
I REALLY REALLY like this sentence.
Nice.

2021-09-17 15:35 UTC, gabrielcossette commented
FR translation review completed 🙂

2021-09-21 14:20 UTC, merged